<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('produk')->insert([
            // Elektronik
            [
                'kategori_id' => 1,
                'supplier_id' => 1,
                'nama' => 'Smartphone A1',
                'sku' => 'EL-001',
                'stok' => 0,
                'min_stok' => 10,
                'unit' => 'pcs',
                'harga' => 2500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'supplier_id' => 2,
                'nama' => 'Laptop ZBook 14',
                'sku' => 'EL-002',
                'stok' => 0,
                'min_stok' => 5,
                'unit' => 'pcs',
                'harga' => 8500000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'supplier_id' => 3,
                'nama' => 'Wireless Earbuds Pro',
                'sku' => 'EL-003',
                'stok' => 0,
                'min_stok' => 15,
                'unit' => 'pcs',
                'harga' => 550000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'supplier_id' => 4,
                'nama' => 'Smartwatch FitX',
                'sku' => 'EL-004',
                'stok' => 0,
                'min_stok' => 8,
                'unit' => 'pcs',
                'harga' => 750000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'supplier_id' => 5,
                'nama' => 'Bluetooth Speaker Mini',
                'sku' => 'EL-005',
                'stok' => 0,
                'min_stok' => 10,
                'unit' => 'pcs',
                'harga' => 300000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Peralatan Rumah Tangga
            [
                'kategori_id' => 2,
                'supplier_id' => 6,
                'nama' => 'Blender UltraMix',
                'sku' => 'RT-001',
                'stok' => 0,
                'min_stok' => 7,
                'unit' => 'pcs',
                'harga' => 450000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'supplier_id' => 7,
                'nama' => 'Rice Cooker 1L',
                'sku' => 'RT-002',
                'stok' => 0,
                'min_stok' => 5,
                'unit' => 'pcs',
                'harga' => 380000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'supplier_id' => 8,
                'nama' => 'Air Fryer 2L',
                'sku' => 'RT-003',
                'stok' => 0,
                'min_stok' => 4,
                'unit' => 'pcs',
                'harga' => 900000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'supplier_id' => 9,
                'nama' => 'Vacuum Cleaner Mini',
                'sku' => 'RT-004',
                'stok' => 0,
                'min_stok' => 6,
                'unit' => 'pcs',
                'harga' => 650000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'supplier_id' => 10,
                'nama' => 'Kipas Angin Meja',
                'sku' => 'RT-005',
                'stok' => 0,
                'min_stok' => 8,
                'unit' => 'pcs',
                'harga' => 200000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Fashion & Apparel
            [
                'kategori_id' => 3,
                'supplier_id' => 11,
                'nama' => 'Kaos Polos Premium',
                'sku' => 'FA-001',
                'stok' => 0,
                'min_stok' => 20,
                'unit' => 'pcs',
                'harga' => 75000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'supplier_id' => 12,
                'nama' => 'Kemeja Slim Fit',
                'sku' => 'FA-002',
                'stok' => 0,
                'min_stok' => 10,
                'unit' => 'pcs',
                'harga' => 150000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'supplier_id' => 13,
                'nama' => 'Jaket Hoodie',
                'sku' => 'FA-003',
                'stok' => 0,
                'min_stok' => 5,
                'unit' => 'pcs',
                'harga' => 220000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'supplier_id' => 14,
                'nama' => 'Celana Jeans Biru',
                'sku' => 'FA-004',
                'stok' => 0,
                'min_stok' => 8,
                'unit' => 'pcs',
                'harga' => 180000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'supplier_id' => 15,
                'nama' => 'Sepatu Sneakers',
                'sku' => 'FA-005',
                'stok' => 0,
                'min_stok' => 5,
                'unit' => 'pasang',
                'harga' => 300000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kebutuhan Kantor
            [
                'kategori_id' => 4,
                'supplier_id' => 16,
                'nama' => 'Buku Catatan A5',
                'sku' => 'KK-001',
                'stok' => 0,
                'min_stok' => 30,
                'unit' => 'pcs',
                'harga' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 4,
                'supplier_id' => 17,
                'nama' => 'Pulpen Hitam',
                'sku' => 'KK-002',
                'stok' => 0,
                'min_stok' => 50,
                'unit' => 'pcs',
                'harga' => 5000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 4,
                'supplier_id' => 18,
                'nama' => 'Stapler Mini',
                'sku' => 'KK-003',
                'stok' => 0,
                'min_stok' => 10,
                'unit' => 'pcs',
                'harga' => 20000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 4,
                'supplier_id' => 19,
                'nama' => 'Penggaris 30cm',
                'sku' => 'KK-004',
                'stok' => 0,
                'min_stok' => 20,
                'unit' => 'pcs',
                'harga' => 7000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 4,
                'supplier_id' => 20,
                'nama' => 'Map Dokumen',
                'sku' => 'KK-005',
                'stok' => 0,
                'min_stok' => 50,
                'unit' => 'pcs',
                'harga' => 3000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kecantikan & Perawatan
            [
                'kategori_id' => 5,
                'supplier_id' => 21,
                'nama' => 'Sabun Wajah Bright',
                'sku' => 'KP-001',
                'stok' => 0,
                'min_stok' => 10,
                'unit' => 'pcs',
                'harga' => 50000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 5,
                'supplier_id' => 22,
                'nama' => 'Sunscreen SPF 50',
                'sku' => 'KP-002',
                'stok' => 0,
                'min_stok' => 8,
                'unit' => 'pcs',
                'harga' => 75000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 5,
                'supplier_id' => 23,
                'nama' => 'Toner Hydrating',
                'sku' => 'KP-003',
                'stok' => 0,
                'min_stok' => 10,
                'unit' => 'pcs',
                'harga' => 65000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 5,
                'supplier_id' => 24,
                'nama' => 'Shampoo Daily Fresh',
                'sku' => 'KP-004',
                'stok' => 0,
                'min_stok' => 10,
                'unit' => 'pcs',
                'harga' => 40000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 5,
                'supplier_id' => 25,
                'nama' => 'Body Lotion Moisture',
                'sku' => 'KP-005',
                'stok' => 0,
                'min_stok' => 8,
                'unit' => 'pcs',
                'harga' => 55000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
